version: "3"

services:
  postgres:
    image: postgres
    volumes:
      - "postgres_data:/var/lib/postgresql/data"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres

  redis:
    image: redis
    volumes:
      - "redis_data:/redis/data"

  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    env_file: .env.prod
    command: yarn prod

volumes:
  redis_data:
  postgres_data:
